name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'pre-commit-ci' ||
      github.actor == 'pre-commit-ci[bot]' ||
      github.actor == 'dependabot[bot]' ||
      github.actor == 'dependabot'
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.13.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          MERGE_METHOD: "rebase"
          MERGE_REMOVE_LABELS: "automerge"
          UPDATE_METHOD: "rebase"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
