name: Github pages

on:
  release:
    types: [published]
  push:
    tags:
      - '*'

jobs:

  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Update permission
      run: |
        chmod +x docs/buildDocs.sh
    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "docs/buildDocs.sh"
      shell: bash
