name: Github pages

on:
  release:
    types: [published]
  push:
    tags:
      - '*'

jobs:

  build_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: seanzhengw/sphinx-pages@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_readme: true
