name: Github pages

on:
  release:
    types: [published]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: seanzhengw/sphinx-pages@master
        id: sphinx-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_readme: true
